import fs from "node:fs";
import path from "node:path";
import { notes, glossary, sourceLedger } from "../lib/atlas-data";

const root = process.cwd();
const outputPath = path.join(root, "worker", "corpus.md");

function formatClaim(claim: { kind: string; label: string; ref: string; quote?: string }) {
  const quote = claim.quote ? ` Quote: "${claim.quote}"` : "";
  return `- [${claim.kind}] ${claim.label} — ${claim.ref}.${quote}`;
}

const header = `# Thunderforge JPP Atlas — Tutor Corpus

You answer questions strictly from the corpus below. It is built from JP 5-0 (Joint Planning, 1 Dec 2020) and Scale AI's public Thunderforge material.

## Source ledger
- **doctrine**: ${sourceLedger.doctrine}
- **scale**: ${sourceLedger.scale}
- **inference**: ${sourceLedger.inference}
- **scenario**: ${sourceLedger.scenario}
`;

const glossarySection = `## Glossary
${Object.entries(glossary)
  .map(([term, def]) => `- **${term}**: ${def}`)
  .join("\n")}
`;

const noteSections = notes.map((note) => {
  const meta: string[] = [`slug: ${note.slug}`, `cluster: ${note.cluster}`];
  if (note.jppStep) meta.push(`jppStep: ${note.jppStep}`);
  if (note.agenticOverlay) meta.push(`agenticOverlay: ${note.agenticOverlay}`);
  meta.push(`tags: ${note.tags.join(", ")}`);

  return `## ${note.title}
${meta.join("\n")}

Summary: ${note.summary}

Source claims:
${note.sourceClaims.map(formatClaim).join("\n")}
`;
});

const combined = [header, glossarySection, ...noteSections].join("\n---\n\n");

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, combined);

const slugsList = notes.map((note) => note.slug);
const generatedTsPath = path.join(root, "worker", "src", "corpus.generated.ts");
fs.mkdirSync(path.dirname(generatedTsPath), { recursive: true });
const tsBody = `// Auto-generated by scripts/build-corpus.ts — do not edit by hand.
export const CORPUS = ${JSON.stringify(combined)};
export const KNOWN_SLUGS: ReadonlySet<string> = new Set(${JSON.stringify(slugsList)});
`;
fs.writeFileSync(generatedTsPath, tsBody);

console.log(`Wrote ${outputPath} (${notes.length} notes, ${Object.keys(glossary).length} glossary terms, ${combined.length} chars)`);
console.log(`Wrote ${generatedTsPath}`);
